# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
