# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-11 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingridients',
            field=models.TextField(),
        ),
    ]
